### ISSUE TITLE
Unable to execute "das gui"

### ISSUE THREAD

**Issue by jenricano** [janclemenslab/das#28]
Hello! I'm using a Mac. I installed using the terminal and I am able to execute the commands "conda activate das" and "das train --help" with no problem. However, when I type in "das gui" and hit enter, I get the following:
<img width="682" alt="Screen Shot 2022-05-03 at 3 42 44 PM" src="https://user-images.githubusercontent.com/104865036/166553651-9076679c-dce0-4c37-ba9f-20de5a0c960f.png">
<img width="297" alt="Screen Shot 2022-05-03 at 3 43 54 PM" src="https://user-images.githubusercontent.com/104865036/166554095-4f3ce587-1549-46e2-a6ef-a8a8836b541f.png">
<img width="403" alt="Screen Shot 2022-05-03 at 3 44 13 PM" src="https://user-images.githubusercontent.com/104865036/166554107-d0bd6612-a41d-4866-bf11-7bb13800cad7.png">

My computer is definitely attempting to run something because it gets loud and hot until I Force Quit the Terminal. Any assistance in getting the program to run would be greatly appreciated.

Best,
Jen

**Comment by postpop** [comment]
Hi Jen,

thanks for reporting this bug! I just tested this and I ran into the same issue.

Must be something with the gui libraries. Installing DAS with python 3.9 (instead of 3.8, as is the default atm) solves the issue:
```shell
mamba create python=3.9 das -c conda-forge -c ncb -n das
```

Let me know if this solves the issue for you. I'll then update the installation instructions accordingly.

**Comment by jenricano** [comment]
That resolved the issue! Thanks so much!
