### ISSUE TITLE
Restart training in COLAB

### ISSUE THREAD

**Issue by CarmenWinters** [janclemenslab/das#30]
I currently am training a model in COLAB. However, I have reached my user limits.
Can I restart training from the last saved epoch? 

Carmen

**Comment by postpop** [comment]
Hi Carmen,

sorry about the late reply. Yes, restarting training is possible. 
See this [notebook](https://gist.github.com/postpop/98c348ccf970093f4f4e71e18b9a4bb6).
Let me know if this works for or if you have more questions.

Jan

**Comment by CarmenWinters** [comment]
Hi Jan,

I am having some other difficulties and I am not sure anymore how to solve them.

So I am working on mouse pup ultrasonic vocalizations (sample rate of 250 kHz).
They are sampled in a rather noisy environment unfortunately (see https://doi.org/10.1038/s41598-022-05641-w), so I high-pass filtered them at 40 kHz.

I than have labeled more than 2000 USVs (with varying amplitudes, ages, sex...) to train. I tried to use the same parameters for training as the mouse model explained in your publication,
but prediction is not going too well.
Here are some issues I seem to have


1.       If I restart training or when I reach the limits of Colab, no _results.h5-file is created, whereas I cannot perform some visualizations

2.       As I labeled the USV's as segments, I wanted to delete detections <1 ms, which gives me following error code:
***@***.***

3.       And this might be linked to 2, the predictions that are generated are looking like events (so start and end time are the exact same).

4.       The predictions that are made do not trace back the USVs even in files which I used for training.

5.       I now just trained on the segments and not the on- or offset, should I include that?

I am so sorry for the many questions, but do you have any suggestions of what I might do wrong?

Kind regards,
Carmen

**Comment by postpop** [comment]
Sorry you run into so many issues and happy to help!

I re-fitted a model to our mice data just to make that we didn't introduce any bugs recently. Still works as before - the post processing (fill short gaps, delete short segments) is crucial to get smooth detections. The defaults (0.02 for both parameters) or the values from the paper should produce reasonable annotations.

1. The results file is created at the end of the `das.train.train` function. If training is interrupted, the file will not be created. I'll update the gist to also generate the results file. Probably a good idea to implement picking up training from an existing model in a future update.
2./3./4. I think there is sth fundamentally off - maybe some bug in the code. Looks like you delete all segments with this and that casues the error. Could you send the model and example data? That would help identifying the source of the error.
5. Including the on- and offsets rarely helps - I think the problem lies elsewhere.

**Comment by postpop** [comment]
The [notebook](https://gist.github.com/postpop/98c348ccf970093f4f4e71e18b9a4bb6) is updated to now also test the model.

**Comment by CarmenWinters** [comment]
Hi Jan,

Thank you for your suggestions! I really would like to use DAS to analyze my data :)

In the following link I have two of my recordings (one recorded on PND5 and one on PND7), the last model and the .yaml-file.
https://filesender.belnet.be/?s=download&token=0c5a4deb-4235-47bb-9bc9-d82d683e356d

I'll retry to fit the model and will let you know whether it worked.

Again, thank you for the help!

**Comment by CarmenWinters** [comment]
Did you detect separate USVs when you run it?
When I run it with these prediction parameters the whole recording is seen as ‘USV’?

**Comment by postpop** [comment]
Yes, I get ~20 detected USVs for the P7... file using these settings. 
Maybe you're on an older version of DAS that has some bugs? Best to re-install DAS to ensure you are on the latest version.
[P7_Mother3_pup1_annotations.csv](https://github.com/janclemenslab/das/files/8870622/P7_Mother3_pup1_annotations.csv)
