### ISSUE TITLE
Segment Thresholds + h5 export in GUI not working?

### ISSUE THREAD

**Issue by callanalexander** [janclemenslab/das#50]
Hi, 

I have noticed that the segment thresholds in the GUI do not seem to be working? My predictions seem to be the same regardless of the threshold settings. 

I have also noticed that export as .h5 does not seem to work, it exports as a .csv even when .h5 is selected. 

I have tested this on windows 10 and 11. Are these known issues?

Working on Das v0.26.8

Otherwise all working great, thanks very much!

**Comment by postpop** [comment]
Hi,

Thresholding works for me in the latest version. Can you update DAS via `pip install das --upgrade --no-deps` and let me know whether that fixes it? Thanks.

Saving as h5 did not work - thanks for reporting that bug! It's now fixed in the latest version of the GUI xarray-behave. Can you update that one via `pip install xarray-behave --upgrade --no-deps`? The fix should appear in the conda package later today.

**Comment by postpop** [comment]
Assuming the fix worked and closing this issue. Please re-open if the issue persists.
